# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('animal_id', models.AutoField(max_length=10, primary_key=True, serialize=False, verbose_name='\u52a8\u7269\u7f16\u53f7')),
                ('station_id', models.IntegerField(verbose_name='\u6551\u52a9\u7ad9\u7f16\u53f7')),
                ('name', models.CharField(max_length=10, verbose_name='\u52a8\u7269\u540d')),
                ('sex', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=6, verbose_name='\u6027\u522b')),
                ('age', models.IntegerField(null=True, verbose_name='\u5e74\u9f84')),
                ('health', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5065\u5eb7\u72b6\u51b5')),
                ('price', models.CharField(default='free', max_length=10, verbose_name='\u4ef7\u683c')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5165\u7ad9\u65e5\u671f')),
                ('species', models.CharField(choices=[('DOG', 'dog'), ('CAT', 'cat'), ('OTHER', 'other')], max_length=4, verbose_name='\u7269\u79cd')),
                ('photo', models.ImageField(null=True, upload_to='animal_img', verbose_name='\u52a8\u7269\u56fe\u7247')),
            ],
        ),
    ]
