# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(max_length=10, primary_key=True, serialize=False, verbose_name='\u8bc4\u8bbaid')),
                ('content', models.CharField(max_length=256, verbose_name='\u5185\u5bb9')),
                ('user_id', models.IntegerField(verbose_name='\u6240\u5c5e\u7528\u6237')),
                ('image', models.ImageField(null=True, upload_to='comment_img', verbose_name='\u8bc4\u8bba\u56fe\u7247')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('likes', models.IntegerField(default=0, verbose_name='\u9876')),
                ('dislikes', models.IntegerField(default=0, verbose_name='\u8e29')),
            ],
            options={
                'db_table': 'comments',
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(max_length=10, primary_key=True, serialize=False, verbose_name='\u5e16\u5b50\u4e3b\u952eID')),
                ('title', models.CharField(max_length=20, verbose_name='\u5e16\u5b50\u6807\u9898')),
                ('content', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u5e16\u5b50\u5185\u5bb9')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u53d1\u5e16\u65f6\u95f4')),
                ('mod_time', models.DateTimeField(auto_now_add=True, verbose_name='\u4fee\u8ba2\u65f6\u95f4')),
                ('image', models.ImageField(null=True, upload_to='post_img', verbose_name='\u8d34\u56fe')),
                ('user_id', models.IntegerField(verbose_name='\u6240\u5c5e\u7528\u6237')),
                ('post_cate', models.CharField(choices=[('FG', 'free_giving'), ('FW', 'free_want'), ('NE', 'new_explorer'), ('TS', 'tell_story')], max_length=2, verbose_name='\u5e16\u5b50\u7c7b\u578b')),
                ('animal_cate', models.CharField(choices=[('DOG', 'dog'), ('CAT', 'cat'), ('OTHER', 'other')], max_length=10, null=True, verbose_name='\u52a8\u7269\u7c7b\u578b')),
                ('comments', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570\u91cf')),
            ],
            options={
                'ordering': ['-mod_time'],
                'db_table': 'posts',
                'verbose_name': '\u5e16\u5b50',
                'verbose_name_plural': '\u5e16\u5b50',
            },
        ),
    ]
