# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('user_id', models.IntegerField(verbose_name='\u6240\u5c5e\u7528\u6237')),
                ('image', models.ImageField(null=True, upload_to='comment_img', verbose_name='\u8bc4\u8bba\u56fe\u7247')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('likes', models.IntegerField(default=0, verbose_name='\u9876')),
                ('dislikes', models.IntegerField(default=0, verbose_name='\u8e29')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u5e16\u5b50\u6807\u9898')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u5e16\u5b50\u5185\u5bb9')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u53d1\u5e16\u65f6\u95f4')),
                ('image', models.ImageField(null=True, upload_to='post_img', verbose_name='\u8d34\u56fe')),
                ('user_id', models.IntegerField(verbose_name='\u6240\u5c5e\u7528\u6237')),
                ('post_cate', models.CharField(choices=[('GV', 'giving'), ('WT', 'want'), ('NE', 'new_explorer'), ('TS', 'tell_story')], max_length=2, verbose_name='\u5e16\u5b50\u7c7b\u578b')),
                ('animal_cate', models.CharField(choices=[('DOG', 'dog'), ('CAT', 'cat'), ('OTHER', 'other')], max_length=10, null=True, verbose_name='\u52a8\u7269\u7c7b\u578b')),
                ('comment_num', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570\u91cf')),
                ('likes', models.IntegerField(default=0, verbose_name='\u9876')),
                ('dislikes', models.IntegerField(default=0, verbose_name='\u8e29')),
            ],
            options={
                'verbose_name': '\u5e16\u5b50',
                'verbose_name_plural': '\u5e16\u5b50',
            },
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Posts', verbose_name='\u5e16\u5b50'),
        ),
    ]
