# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20170702_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u8bc4\u8bba\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e16\u65f6\u95f4'),
        ),
    ]
