# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('secret', 'SECRET')], default='SECRET', max_length=6, null=True, verbose_name='\u6027\u522b'),
        ),
    ]
