# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20170621_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='kind',
            field=models.CharField(max_length=100, verbose_name='\u7528\u6237\u7c7b\u578b'),
        ),
    ]
