# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5165\u7ad9\u65e5\u671f'),
        ),
    ]
